my_user:
    resource: "@MyUserBundle/Resources/config/routing.yml"
    prefix:   /

my_telemedicine:
    resource: "@MyTelemedicineBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    path: /login
    defaults: { _controller: MyTelemedicineBundle:Security:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    


