tusers:
    path:     /
    defaults: { _controller: "MyTelemedicineBundle:TUsers:index" }

tusers_show:
    path:     /{id}/show
    defaults: { _controller: "MyTelemedicineBundle:TUsers:show" }

tusers_new:
    path:     /new
    defaults: { _controller: "MyTelemedicineBundle:TUsers:new" }

tusers_create:
    path:     /create
    defaults: { _controller: "MyTelemedicineBundle:TUsers:create" }
    requirements: { _method: post }

tusers_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyTelemedicineBundle:TUsers:edit" }

tusers_update:
    path:     /{id}/update
    defaults: { _controller: "MyTelemedicineBundle:TUsers:update" }
    requirements: { _method: post|put }

tusers_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyTelemedicineBundle:TUsers:delete" }
    requirements: { _method: post|delete }
