my_telemedicine_tusers:
    resource: "@MyTelemedicineBundle/Resources/config/routing/tusers.yml"
    prefix:   /tusers

my_telemedicine_homepage:
    path:     /index/
    defaults: { _controller: MyTelemedicineBundle:Default:index }

my_telemedicine_telemetry:
    path: /telemetry/
    defaults: { _controller: MyTelemedicineBundle:Default:telemetry }
    
my_telemedicine_formularios:
    path: /formularios/
    defaults: { _controller: MyTelemedicineBundle:Default:formularios }
    
my_telemedicine_test:
    path: /test/
    defaults: { _controller: MyTelemedicineBundle:Default:test }