my_telemedicine_tusers:
    resource: "@MyTelemedicineBundle/Resources/config/routing/tusers.yml"
    prefix:   /tusers

my_telemedicine_homepage:
    path: /{_locale}/index/
    defaults: { _controller: MyTelemedicineBundle:Default:index }
    requirements:
        _locale: en|es
   


my_telemedicine_telemetry:
    path: /{_locale}/telemetry/
    defaults: { _controller: MyTelemedicineBundle:Default:telemetry }
    requirements:
        _locale: en|es
    
my_telemedicine_formularios:
    path: /formularios/
    defaults: { _controller: MyTelemedicineBundle:Default:formularios }
    
my_telemedicine_test:
    path: /test/
    defaults: { _controller: MyTelemedicineBundle:Default:test }


     