parameters:
    ruido: BRUM
    noise: BROOOMMMMMMMM
    my_measure.class:  My\TelemedicineBundle\Entity\TMeasures

services:
#    my_telemedicine.example:
#        class: My\TelemedicineBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]





 my_telemedicine.type.measure_selector:
        class: My\TelemedicineBundle\Form\Type\MeasureSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
                - { name: form.type, alias: measure_selector }
                

                
                
                
 my_telemedicine.model.Coche:
    class: My\TelemedicineBundle\Model\Coche
    arguments: [%ruido%,%noise%]
   
    
 my_telemedicine.TUsers_listener:
    class: My\TelemedicineBundle\Event\TUsersListener
    arguments:
        logger: "@logger"
    tags:
        - { name: kernel.event_listener, event: foo.action, method: onFooAction }
        
    


    
    
    
    
    
    

    
    
    
    
    
    
